services:
  postgres:
    image: 'postgres:16.3-alpine'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}
  redis:
    image: 'redis:7.4'
    ports:
      - '6379'
  mockoon:
    image: 'mockoon/cli:9'
    container_name: mockoon-mock
    volumes:
      - ./mockoon-mock.json:/data/mockoon-mock.json
    command: [ "-d", "/data/mockoon-mock.json" ]
    ports:
      - "3000:3000"
volumes:
  postgres_data:
    driver: local
